### ISSUE TITLE
question regarding deploying on deeplens

### ISSUE THREAD

**Issue by jlwebuser** [alexschultz/ReadToMe#3]
Hi, this is a really neat project - thanks for sharing.

I am new to the deeplens. I follow the sagemaker part, but I'm having a hard time figuring out exactly how to deploy the project.

Is the following correct?

in Deeplens Admin Page - Create a new blank project
then Add the trained model (uploaded to S3) to the project

Add a new Function ? - this is where I get lost. I think I need to add ReadToMeLambda.py as the function to execute on deeplens, (along with the sounds properties).  But I am not clear what other files need to go up, does the entire deeplens-lambda-read-to-me  get uploaded into s3?  and deployed somehow to the DeepLens.  

any pointers are appreciated, sorry if I'm missing something obvious.
Regards,
john

**Comment by alexschultz** [comment]
Thanks John, 
The Lambda function includes all the content here:
https://github.com/alexschultz/ReadToMe/tree/master/deeplens-lambda-read-to-me

You need to zip up those files and then upload the zip as the lambda function using the upload button in the Function Code section of the Lambda module.

see below

<img width="1277" alt="screen shot 2018-11-29 at 6 04 50 pm" src="https://user-images.githubusercontent.com/1521763/49263960-61567200-f401-11e8-8d73-f5f44c507c6d.png">


Also, make sure you specify the correct handler to invoke in the Lambda 
i.e. "readToMeLambda.greengrass_infinite_infer_run"


The documentation for creating custom projects is here:
https://docs.aws.amazon.com/deeplens/latest/dg/deeplens-custom-projects.html
There is a section for how to reference an externally trained model as well as how to create the project to deploy to the DeepLens.

Sorry, it's not entirely obvious how to setup this project. Feel free to watch this repo. As soon as I get some time, I plan to make better instructions available that are clearer for people to follow along. Let me know if you get stuck in the meantime.

**Comment by jlwebuser** [comment]
Thanks for the quick reply and the info. Really appreciate the help.
Best,
--
John
t: @jlwebuser
