### ISSUE TITLE
Playsound issue

### ISSUE THREAD

**Issue by NalikeTalha** [alexschultz/ReadToMe#5]

**Comment by NalikeTalha** [comment]
hi i am having problem installing the requirement dependencies its giving me an error

ERROR: You must give at least one requirement to install (maybe you meant "pip install requirements.txt"?)

**Comment by NalikeTalha** [comment]
i need that fixed for a project i would be grateful if you could help

**Comment by b1ue-guy-talha** [comment]
i need that fixed for a project i would be grateful if you could help

**Comment by b1ue-guy-talha** [comment]
i need that fixed for a project i would be grateful if you could help

**Comment by alexschultz** [comment]
Hey sorry about that, the command should be:
pip install -r requirements.txt

I accidentally put -f, which is wrong.

**Comment by NalikeTalha** [comment]
okay thanks
can you help me in my project

**Comment by b1ue-guy-talha** [comment]
my whatsapp is +973 37247334
if u can contact on whatsapp

**Comment by NalikeTalha** [comment]
can you send me mail in talhaa9299@gmail.com

**Comment by alexschultz** [comment]
closing this now, if you still have trouble feel free to reopen

**Comment by NalikeTalha** [comment]
okay thanks
